name: moneyflow
description: Your app description

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  qr_flutter: ^4.1.0
  intl: ^0.18.0
  shared_preferences: ^2.0.0
  provider: ^6.0.0
  
  
  # Networking
  http: ^1.1.0
  dio: ^5.3.2  # Pour l'implémentation Dio
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # State Management (si vous utilisez bloc)
  flutter_bloc: ^8.1.3
  
  # Utilities
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  http_proxy: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  assets:
    - assets/images/logo.png
    - assets/images/carte.png

